defmodule AutonomousOpponentV2Core.AMCP.Message do
  @moduledoc """
  Defines the Advanced Model Context Protocol (aMCP) message structure.
  This struct represents the standardized format for all messages flowing through the Cybernetic system.

  **Wisdom Preservation:** A well-defined message schema is crucial for interoperability,
  traceability, and ensuring that all components understand the 'meaning' of data.
  It prevents implicit contracts and facilitates future evolution.
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  embedded_schema do
    field :id, :binary_id, primary_key: true # ID should be a content-based hash, not autogenerated
    field :type, :string
    field :sender, :string
    field :recipient, :string
    field :payload, :map
    field :context, :map
    field :timestamp, :utc_datetime, autogenerate: {&DateTime.utc_now/0, [], UtcDateTime}
    field :signature, :string
  end

  @doc false
  def changeset(message, attrs) do
    message
    |> cast(attrs, [:id, :type, :sender, :recipient, :payload, :context, :timestamp, :signature])
    |> validate_required([:id, :type, :sender, :payload, :context, :timestamp])
  end
end
