defmodule AutonomousOpponentV2Web.ErrorJSON do
  # If you want to customize a particular status code
  # for a certain format, you may sure a view similar to
  # the following. If no view is defined, a default one is
  # generated by Phoenix unless specified otherwise.
  def render("500.json", _assigns) do
    %{errors: %{detail: "Internal Server Error"}}
  end
end
