defmodule AutonomousOpponentV2Web.ErrorJSON do
  # If you want to customize a particular status code
  # for a certain format, you may sure a view similar to
  # the following. If no view is defined, a default one is
  # generated by Phoenix unless specified otherwise.
  
  # This template is invoked when no function clause matches
  # in the ErrorJSON module
  def render(template, _assigns) do
    %{errors: %{detail: Phoenix.Controller.status_message_from_template(template)}}
  end
  
  def render("400.json", _assigns) do
    %{errors: %{detail: "Bad Request"}}
  end
  
  def render("401.json", _assigns) do
    %{errors: %{detail: "Unauthorized"}}
  end
  
  def render("403.json", _assigns) do
    %{errors: %{detail: "Forbidden"}}
  end
  
  def render("404.json", _assigns) do
    %{errors: %{detail: "Not Found"}}
  end
  
  def render("422.json", _assigns) do
    %{errors: %{detail: "Unprocessable Entity"}}
  end
  
  def render("500.json", _assigns) do
    %{errors: %{detail: "Internal Server Error"}}
  end
  
  def render("503.json", _assigns) do
    %{errors: %{detail: "Service Unavailable"}}
  end
end
