import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :autonomous_opponent_web, AutonomousOpponentV2Web.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: AutonomousOpponent.Finch

# Do not print debug messages in production
config :logger, level: :info

# LLM Response Cache Configuration for Production
config :autonomous_opponent_core,
  # Enable LLM response caching in production
  llm_cache_enabled: true,

  # Production cache settings
  llm_cache_config: [
    # Larger cache size for production
    max_size: 5000,

    # Default TTL: 2 hours
    ttl: 7_200_000,

    # Warm cache from disk on startup
    warm_on_start: true,

    # Persist cache to disk every 10 minutes
    persist_interval: 600_000
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
