name: VSM CI/CD with Claude Intelligence

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

env:
  MIX_ENV: test
  ELIXIR_VERSION: 1.16.3
  OTP_VERSION: 26.2.5

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: read

jobs:
  # S4 Intelligence Analysis
  intelligence-analysis:
    name: S4 - Intelligence Analysis
    runs-on: ubuntu-latest
    outputs:
      quality_trend: ${{ steps.analyze.outputs.quality_trend }}
      risk_level: ${{ steps.analyze.outputs.risk_level }}
      needs_claude_insight: ${{ steps.analyze.outputs.needs_claude }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Analyze Patterns
      id: analyze
      run: |
        # Standard analysis
        RECENT_COMMITS=$(git log --oneline -n 50 --pretty=format:"%s")
        BUG_FIXES=$(echo "$RECENT_COMMITS" | grep -ci "fix\|bug" || true)
        FEATURES=$(echo "$RECENT_COMMITS" | grep -ci "feat\|add" || true)
        
        # Determine if we need Claude's insight
        if [ $BUG_FIXES -gt 5 ]; then
          echo "needs_claude=true" >> $GITHUB_OUTPUT
          echo "risk_level=high" >> $GITHUB_OUTPUT
          echo "::warning::High bug count detected - requesting Claude analysis"
        else
          echo "needs_claude=false" >> $GITHUB_OUTPUT
          echo "risk_level=medium" >> $GITHUB_OUTPUT
        fi

  # Claude S4 Intelligence Enhancement
  claude-intelligence:
    name: Claude S4 Intelligence Enhancement
    runs-on: ubuntu-latest
    needs: intelligence-analysis
    if: |
      needs.intelligence-analysis.outputs.needs_claude == 'true' &&
      github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Request Claude Analysis
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          const comment = `@claude As our S4 Intelligence layer, please analyze this PR:
          
          **S4 Intelligence Request:**
          - Recent bug fix count is high (potential instability)
          - Analyze the changes for systemic issues
          - Recommend S5 policy adjustments
          - Identify emergence patterns
          
          Focus on VSM viability and cybernetic stability.`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            body: comment
          });

  # Algedonic Pain Response with Claude
  algedonic-claude-response:
    name: Algedonic Claude Response
    runs-on: ubuntu-latest
    if: |
      failure() && 
      github.event_name == 'pull_request'
    needs: [test-operations, code-quality]
    
    steps:
    - name: Trigger Claude Pain Analysis
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          const comment = `@claude **🚨 ALGEDONIC PAIN SIGNAL DETECTED**
          
          The VSM system is experiencing pain in this PR:
          - Test failures: ${{ needs.test-operations.result }}
          - Quality issues: ${{ needs.code-quality.result }}
          
          As our augmented intelligence, please:
          1. Diagnose the root cause
          2. Suggest immediate remediation
          3. Recommend systemic improvements
          
          This is a high-priority algedonic response.`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            body: comment
          });

  # Standard CI/CD jobs...
  code-quality:
    name: S2 - Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Quality Checks
      run: echo "Quality checks here"

  test-operations:
    name: S1 - Test Operations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: echo "Tests here"